select-findAllSocios = SELECT id, nombre, apellidos, dni, fecha_nacimiento, direccion, fecha_inscripcion, es_titular, titulo_patron FROM socios;
select-findSocioById = SELECT id, nombre, apellidos, dni, fecha_nacimiento, direccion, fecha_inscripcion, es_titular, titulo_patron FROM socios WHERE id=?;
insert-addSocio = INSERT INTO socios (id, nombre, apellidos, dni, fecha_nacimiento, direccion, fecha_inscripcion, es_titular, titulo_patron) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);


select-findAllAlquileres = SELECT id, fechainicio, fechafin, precio, plazas, usuario_dni, matricula_embarcacion, acompanantes_dni FROM alquileres;
select-findAlquilerById = SELECT id, fechainicio, fechafin, precio, plazas, usuario_dni, matricula_embarcacion, acompanantes_dni FROM alquileres WHERE id=?;
insert-addAlquiler = INSERT INTO alquileres (id, fechainicio, fechafin, precio, plazas, usuario_dni, matricula_embarcacion, acompanantes_dni) VALUES (?, ?, ?, ?, ?, ?, ?, ?);


select-findAllReservas = SELECT id, fecha, plazas, precio, usuario_id, matricula_embarcacion, descripcion FROM reservas;
select-findReservaById = SELECT id, fecha, plazas, precio, usuario_id, matricula_embarcacion, descripcion FROM reservas WHERE id=?;
insert-addReserva = INSERT INTO reservas (id, fecha, plazas, precio, usuario_id, matricula_embarcacion, descripcion) VALUES (?, ?, ?, ?, ?, ?, ?);