select-findAllSocios = SELECT id, nombre, apellidos, dni, fecha_nacimiento, direccion, fecha_inscripcion, es_titular, titulo_patron FROM socios;
select-findSocioById = SELECT id, nombre, apellidos, dni, fecha_nacimiento, direccion, fecha_inscripcion, es_titular, titulo_patron FROM socios WHERE id=?;
insert-addSocio = INSERT INTO socios (id, nombre, apellidos, dni, fecha_nacimiento, direccion, fecha_inscripcion, es_titular, titulo_patron) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
