############################################
# SOCIOS
############################################
select-findAllSocios = SELECT nombre, apellidos, dni, fecha_nacimiento, direccion, fecha_inscripcion, es_titular, titulo_patron FROM socios;
select-findSocioByDNI = SELECT nombre, apellidos, dni, fecha_nacimiento, direccion, fecha_inscripcion, es_titular, titulo_patron FROM socios WHERE dni=?;
insert-addSocio = INSERT INTO socios (nombre, apellidos, dni, fecha_nacimiento, direccion, fecha_inscripcion, es_titular, titulo_patron) VALUES (?, ?, ?, ?, ?, ?, ?, ?);

############################################
# PATRONES
############################################
select-findAllPatrones = SELECT nombre, apellidos, dni, fecha_nacimiento, fecha_expedicion_titulo FROM patron;
select-findAllFreePatrones = SELECT p.* FROM patron p LEFT JOIN embarcacion e ON p.dni = e.id_patron WHERE e.id_patron IS NULL;
select-findPatronByDNI = SELECT nombre, apellidos, dni, fecha_nacimiento, fecha_expedicion_titulo FROM patron WHERE dni=?;
insert-addPatron = INSERT INTO patron (nombre, apellidos, dni, fecha_nacimiento, fecha_expedicion_titulo) VALUES (?, ?, ?, ?, ?);
select-countPatronByDNI = SELECT COUNT(*) FROM patron WHERE dni = ?;

############################################
# EMBARCACIONES
############################################
select-findAllEmbarcaciones = SELECT matricula, nombre, tipo, plazas, dimensiones, id_patron FROM embarcacion;
select-findEmbarcacionByMatricula = SELECT matricula, nombre, tipo, plazas, dimensiones, id_patron FROM embarcacion WHERE matricula=?;
select-findEmbarcacionByNombre = SELECT matricula, nombre, tipo, plazas, dimensiones, id_patron FROM embarcacion WHERE nombre=?;
select-findAllEmbarcacionesByTipo = SELECT matricula, nombre, tipo, plazas, dimensiones, id_patron FROM embarcacion WHERE tipo=?;
insert-addEmbarcacion = INSERT INTO embarcacion (matricula, nombre, tipo, plazas, dimensiones, id_patron) VALUES (?, ?, ?, ?, ?, NULLIF(?, ''));
select-isPatronAssignedToEmbarcacion = SELECT COUNT(*) FROM embarcacion WHERE id_patron = ?;
select-getPatronAssignedToEmbarcacion = SELECT id_patron FROM embarcacion WHERE matricula = ?;
update-updatePatron = UPDATE embarcacion SET id_patron = ? WHERE matricula = ?
update-updateEmbarcacion = UPDATE embarcacion SET nombre = ?, tipo = ?, plazas = ?, dimensiones = ? WHERE matricula = ?

############################################
# ALQUILERES
############################################
select-findAllAlquileres = SELECT id, fechainicio, fechafin, precio, plazas, usuario_dni, matricula_embarcacion FROM alquiler;
select-findAlquilerById = SELECT id, fechainicio, fechafin, precio, plazas, usuario_dni, matricula_embarcacion FROM alquiler WHERE id=?;
insert-addAlquiler = INSERT INTO alquiler (fechainicio, fechafin, precio, plazas, usuario_dni, matricula_embarcacion) VALUES (?, ?, ?, ?, ?, ?);
select-lastInsertedAlquilerId = SELECT LAST_INSERT_ID();
update-updateAlquiler = UPDATE alquiler SET fechainicio = ?, fechafin = ?, precio = ?, plazas = ?, usuario_dni = ?, matricula_embarcacion = ? WHERE id = ?;
delete-deteleAlquiler = DELETE FROM alquiler WHERE id = ?;

############################################
# RESERVAS
############################################
select-findAllReservas = SELECT id, fecha, plazas, precio, usuario_id, matricula_embarcacion, descripcion FROM reserva;
select-findReservaById = SELECT id, fecha, plazas, precio, usuario_id, matricula_embarcacion, descripcion FROM reserva WHERE id=?;
insert-addReserva = INSERT INTO reserva (fecha, plazas, precio, usuario_id, matricula_embarcacion, descripcion) VALUES (?, ?, ?, ?, ?, ?);
update-reserva = UPDATE Reserva SET fecha = ?, plazas = ?, precio = ?, descripcion = ? WHERE id = ?
delete-reserva = DELETE FROM Reserva WHERE id = ?

############################################
# INSCRIPCIONES
############################################
select-findAllInscripciones = SELECT id, socio_Titular, cuota_anual, fecha_creacion, segundo_adulto from inscripcion;
select-findInscripcionById = SELECT id, socio_Titular, cuota_anual, fecha_creacion, segundo_adulto FROM inscripcion WHERE id=?;
select-findInscripcionByDniTitular = SELECT id, socio_Titular, cuota_anual, fecha_creacion, segundo_adulto FROM inscripcion WHERE socio_Titular=?;
insert-addInscripcion = INSERT INTO inscripcion (socio_Titular, cuota_anual, fecha_creacion) VALUES (?, ?, ?);
update-Inscripcion = UPDATE inscripcion SET  cuota_anual=?, fecha_creacion=?, segundo_adulto=? WHERE id=?;

############################################
# HIJOS
############################################
select-findAllHijos = SELECT dni, nombre, apellidos, fecha_nacimiento, id_inscripcion FROM hijos;
select-findHijoByDNI = SELECT dni, id_inscripcion FROM hijos WHERE dni=?;
select-findHijosByInscripcion = SELECT dni, nombre, apellidos, fecha_nacimiento, id_inscripcion FROM hijos Where id_inscripcion=?;
insert-addHijo = INSERT INTO hijos (dni, nombre, apellidos, fecha_nacimiento, id_inscripcion) VALUES (?, ?, ?, ?, ?);

############################################
# ACOMPANANTES
############################################
select-findAllAcompanantes = SELECT id, dni, id_alquiler FROM acompanantes;
select-findAcompananteByDNI = SELECT id, dni, id_alquiler FROM acompanantes WHERE dni=?;
select-findAcompanantesByAlquiler = SELECT id, dni, id_alquiler FROM acompanantes WHERE id_alquiler=?;
insert-addAcompanante = INSERT INTO acompanantes (dni, id_alquiler) VALUES (?, ?);
delete-deleteAcompanantesByAlquiler = DELETE FROM acompanantes WHERE id_alquiler = ?;
delete-deleteAcompanante = DELETE FROM acompanantes WHERE id_alquiler = ? AND dni = ?;
